### ISSUE TITLE
Add support for soil parameter options like organic_fract

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/tonic#34]
Add support for the following options:
organic_fract
spatial_snow
spatial_frost
july_tavg_supplied

**Comment by jhamman** [comment]
in which utilities?

**Comment by tbohn** [comment]
grid_params.py has the beginnings of this, but not fully implemented.  So, the wires just need to be finished hooking up.  I'm basically doing this as I make other changes for lake and blowing snow parameters.

**Comment by tbohn** [comment]
this was addressed by PR #40 - for some reason this didn't automatically get closed.  But it can be closed now.

**Comment by tbohn** [comment]
Wait, never mind.  The reason it didn't get closed was because I said it shouldn't be closed yet.  The idea being that this issue pertains to the reverse direction (netcdf to ascii) as well as ascii to netcdf, and this hasn't been addressed yet.

**Comment by tbohn** [comment]
The ascii-netcdf conversion aspect of this issue has been addressed in PR #40.  The netcdf-ascii conversion aspect of this issue has been moved into a new issue #44.  Thus, this issue can be closed.

**Comment by tbohn** [comment]
@jhamman just a reminder that this issue can be closed (see my previous comment in the thread).
