### ISSUE TITLE
Some variables in grid params should be an integers not a floats

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/tonic#42]
- overstory
- Ctype
- Nscale
- fs_active
- lake_idx
- numnod
- Nveg

**Comment by tbohn** [comment]
@jhamman - I'm not sure what version of grid_params.py you've been using, but the version I committed and you merged into master with PRs #39, #40, and #41 makes all of those variables ints.

**Comment by jhamman** [comment]
Great.  I think I was looking at the wrong version.
